"""add users table

Revision ID: 18aebc1bf3fb
Revises: 7eb51efe293e
Create Date: 2022-05-23 17:44:36.277531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18aebc1bf3fb'
down_revision = '7eb51efe293e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('football_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('football_match', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score')
    )
    op.create_index(op.f('ix_football_results_id'), 'football_results', ['id'], unique=False)
    op.create_table('nhl_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhl_match', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score')
    )
    op.create_index(op.f('ix_nhl_results_id'), 'nhl_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nhl_results_id'), table_name='nhl_results')
    op.drop_table('nhl_results')
    op.drop_index(op.f('ix_football_results_id'), table_name='football_results')
    op.drop_table('football_results')
    # ### end Alembic commands ###
