"""add users table

Revision ID: 9a4d08169069
Revises: 18aebc1bf3fb
Create Date: 2022-05-23 19:33:09.078505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4d08169069'
down_revision = '18aebc1bf3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('football_results_score_key', 'football_results', type_='unique')
    op.drop_constraint('nhl_results_score_key', 'nhl_results', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('nhl_results_score_key', 'nhl_results', ['score'])
    op.create_unique_constraint('football_results_score_key', 'football_results', ['score'])
    # ### end Alembic commands ###
